version: '3.7'
services:
  transmission:
    build: .
    command: ['/openvpn/start-transmission']
    dns:
      - 85.203.37.1
      - 85.203.37.2
    ports:
      - '9091:9091'
    privileged: true
    volumes:
      - /Volumes/Media/Transmission:/transmission
